server:
  port: 8002

spring:
  logging:
    level:
      org.springframework: DEBUG
  config:
    import:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ccdccd
    url: jdbc:mysql://localhost:3306/footballpairingDB?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    scan:
      packages: com.example.footballpairing.entity
    show-sql: true
    properties:
      hibernate:
        format_sql: true